<?php

function brukar_role_user_login(&$edit, $account) {
  if (isset($account->data['brukar']) && isset($account->data['brukar']['role'])) {
    // TODO Remove 'brukar %'-roles from the user
    // $roles = $account->roles;

    // Fetch or create role
  	$role = user_role_load_by_name('brukar ' . $account->data['brukar']['role']);
  	if ($role === false) {
  	  $role = new stdClass();
      $role->name = 'brukar ' . $account->data['brukar']['role'];
      $role->weight = 2;
      user_role_save($role);
  	}
  	
  	// TODO Add role to user
  	// if ($account->roles != $roles)
  	// user_save($account, array('roles' => $roles));
  }
} 