<?php

/**
 * Helper function for profiles.
 *
 *   function hook_install_tasks() {
 *     return array(
 *       'brukar_install_task' => array(
 *         'display_name' => st('Brukar'),
 *         'type' => 'form',
 *       ),
 *     );
 *   }
 */
function brukar_install_task($form) {
  require_once(drupal_get_path('module', 'brukar') . '/brukar.admin.php');
  return brukar_admin($form);
}

/**
 * Implements hook_menu().
 */
function brukar_menu() {
  $items['admin/config/people/brukar'] = array(
    'title' => 'Brukar',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('brukar_admin'),
    'access arguments' => array('brukar admin'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'brukar.admin.php',
  );
  $items['admin/config/people/brukar/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function brukar_menu_alter(&$items) {
  if (variable_get('brukar_dup', '0') == 1) {
    $items['user']['page arguments'] = array($items['user']['page callback']);
    $items['user']['page callback'] = 'brukar_user_page';
    $items['user']['access callback'] = 'brukar_user_page_access';

    unset($items['user/register']);
    unset($items['user/password']);
    unset($items['user/reset/%/%/%']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds link to login form if brukar isn't hidden.
 */
function brukar_form_user_login_alter(&$form, &$form_state, $form_id) {
  $form['brukar'] = array(
    '#markup' => l('Logg inn med brukar.', $_GET['q'], array('query' => $_GET + array('brukar' => NULL))),
  );
}

/**
 * Implements hook_init().
 */
function brukar_init() {
  // Handle callback
  if (isset($_GET['oauth_token'])) {
    require_once(drupal_get_path('module', 'brukar') . '/brukar.oauth.php');
    brukar_oauth_callback();
  }

  if (user_is_anonymous()) {
    // Forced login
    if (variable_get('brukar_forced', '0') != 0)
      brukar_user_trigger();

    // Magic login
    if (isset($_GET[variable_get('brukar_keyword', 'brukar')]))
      brukar_user_trigger();
  }
}

/**
 * Reimplements user_page().
 */
function brukar_user_page($func = 'user_page') {
  return user_is_logged_in() ? call_user_func($func) : brukar_user_trigger();
}

/**
 * Trigger login
 */
function brukar_user_trigger() {
  // Do login on /user if allowed
  if ($_GET['q'] == 'user' && variable_get('brukar_hidden', 0) == 0)
    $_GET['q'] = isset($_GET['destination']) ? $_GET['destination'] : '<front>';

  // Remove keywork from URI if found
  if (isset($_GET[variable_get('brukar_keyword', 'brukar')]))
    unset($_GET[variable_get('brukar_keyword', 'brukar')]);

  // Fetch request token IF you are supposed to be allowed
  if (variable_get('brukar_url', '') != '') {
    require_once(drupal_get_path('module', 'brukar') . '/brukar.oauth.php');
    return brukar_oauth_request();
  }
}

/**
 * Controls access to /user.
 */
function brukar_user_page_access() {
  return (user_is_logged_in() || variable_get('brukar_hidden', 0) == 0);
}

/**
 * Implements hook_user_view_alter().
 */
function brukar_user_view_alter(&$build) {
  global $user;

  if (!isset($user->data['brukar']))
    $build['brukar'] = drupal_get_form('brukar_form_login');
}

/**
 * Form containing one button to trigger forced login.
 */
function brukar_form_login($form, &$form_state) {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Logg inn med brukar',
  );

  return $form;
}

/**
 * Trigger forced login because the button in the form are used.
 */
function brukar_form_login_submit($form, &$form_state) {
  brukar_user_trigger();
}

/**
 * Implements hook_user_load().
 */
function brukar_user_load($users) {
  foreach ($users as $uid => $user) {
    if (isset($user->data['brukar'])) {
      $user->cellphone = isset($user->data['brukar']['cellphone']) ? $user->data['brukar']['cellphone'] : $user->data['brukar']['phone'];
      $user->organization = $user->data['brukar']['organization'];
      $user->homepage = $user->data['brukar']['homepage'];
    }

    $users[$uid] = $user;
  }
}

/**
 * Implements hook_username_alter().
 */
function brukar_username_alter(&$name, $account) {
  if (isset($account->data) && is_array($account->data) && isset($account->data['brukar']))
    $name = $account->data['brukar']['name'];
}